# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'maxpetretta/tmux-monokai-pro'
set -g @plugin 'tmux-plugins/tmux-yank'

# Set prefix
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# Navigation
set-option -sg escape-time 10
set-option -g focus-events on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*256col*:Tc"
set-option -sa terminal-features ",xterm-256color:RGB"

# Vi mode
set -g mode-keys vi  
setw -g mode-keys vi  
set-window-option -g mode-keys vi

# Smart pane switching with awareness of Vim splits.
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Copy mode key bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Enable mouse support
set -g mouse on

# Clipboard integration
set -g set-clipboard on

# Run plugin manager
run '~/.tmux/plugins/tpm/tpm'
